### ISSUE TITLE
Peer review - Ben

### ISSUE THREAD

**Issue by bendavies0804** [ConnorJ88/OOP-Assignment1#1]
Is the code properly documented/commented?

- The code is properly documented, with 3 files; Pack, Program and Card
- The comments are very good. They are useful and fairly often but there isn't so many that it makes the code difficult to look at.
- I have no Improvements to suggest about comments or documentation.

**Comment by bendavies0804** [comment]
Does the code handle errors properly?

- There is clear evidence of error handling throughout the code, such as not allowing the user to put in a string when an integer is expected.
- However when you are choosing the shuffle, if the integer value is out of range then the code just shuts down, so this is something you might want to address.
- Also, when choosing the number of cards to output, if the number is above 52 then 52 cards are output and if its below 0 then the code just closes.
- However as I mentioned earlier there is clear evidence of basic error handling which is a good start.

**Comment by bendavies0804** [comment]
What suggestions do you have to improve the code? 

- The only suggestions I have to improving the code would be to just implement the advanced error handling which I pointed at before, apart from that the code is very good, performs the two shuffles and therefore does exactly as asked by the brief.

**Comment by ConnorJ88** [comment]
Thanks! I have updated the code so that integers out of range no longer crash the code
